name: Documentation

on:
  push:
    branches:
      - main
      - doc

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: doxygen
        uses: mattnotmitt/doxygen-action@v1.1.0
        with:
          working-directory: "doc"
          doxyfile-path: "Doxyfile"
      - name: gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: doc/html